USE [master]
GO
/****** Object:  Database [ENCUESTAS]    Script Date: 26/3/2024 12:49:57 ******/
CREATE DATABASE [ENCUESTAS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ENCUESTAS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ENCUESTAS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ENCUESTAS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ENCUESTAS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ENCUESTAS] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ENCUESTAS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ENCUESTAS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ENCUESTAS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ENCUESTAS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ENCUESTAS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ENCUESTAS] SET ARITHABORT OFF 
GO
ALTER DATABASE [ENCUESTAS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ENCUESTAS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ENCUESTAS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ENCUESTAS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ENCUESTAS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ENCUESTAS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ENCUESTAS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ENCUESTAS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ENCUESTAS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ENCUESTAS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ENCUESTAS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ENCUESTAS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ENCUESTAS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ENCUESTAS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ENCUESTAS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ENCUESTAS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ENCUESTAS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ENCUESTAS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ENCUESTAS] SET  MULTI_USER 
GO
ALTER DATABASE [ENCUESTAS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ENCUESTAS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ENCUESTAS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ENCUESTAS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ENCUESTAS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ENCUESTAS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ENCUESTAS] SET QUERY_STORE = OFF
GO
USE [ENCUESTAS]
GO
/****** Object:  Table [dbo].[DatosEncuesta]    Script Date: 26/3/2024 12:49:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DatosEncuesta](
	[NumeroEncuesta] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nchar](50) NOT NULL,
	[Apellido] [nchar](100) NOT NULL,
	[FechaNacimiento] [nchar](50) NOT NULL,
	[Edad] [int] NOT NULL,
	[CorreoElectronico] [nchar](100) NOT NULL,
	[CarroPropio] [nchar](50) NOT NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [ENCUESTAS] SET  READ_WRITE 
GO
